name: 🛡️ DevSecOps Security Gate

on:
  pull_request:
    branches: [ main ]

jobs:
  secret-scan:
    name: Secret & API Key Scan
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history so we can scan commits

      - name: 🔍 Run TruffleHog Secret Scanner
        uses: trufflesecurity/trufflehog@main
        with:
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }}
          extra_args: --debug --only-verified